services:
  client:
    build: ./client
    ports:
      - "5000:5000"
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - server

  server:
    restart: always
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - "3000:3000"
  mongo:
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - "27017:27017"
networks:
  react-express:
  express-mongo: