
POST http://localhost:3000/api/data

{
  "activity": "Play a video game",
  "type": "recreational",
  "participants": 1,
  "price": 0,
  "link": "",
  "key": "5534113",
  "accessibility": 0,
  "link": ""
}