
POST http://localhost:3000/api/data
content-type: application/json

{
  "description": "Play a video game",
  "type": "recreational",
  "price": 0,
  "participants": 1,
  "link": "",
  "key": "5534113",
  "accessibility": 0,
  "link": ""
}

###

GET http://localhost:3000/favorites